import {
  SiApacheairflow,
  SiApachespark,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFlask,
  SiGooglebigquery,
  SiGooglecloud,
  SiGooglegemini,
  SiHtml5,
  SiJavascript,
  SiJupyter,
  SiLooker,
  SiNextdotjs,
  SiNumpy,
  SiOpencv,
  SiOpenjdk,
  SiPandas,
  SiPlotly,
  SiPostgresql,
  SiPowerbi,
  SiPython,
  SiPytorch,
  SiReact,
  SiScikitlearn,
  SiStreamlit,
  SiTypescript,
} from "react-icons/si";
import type { IconType } from "react-icons";

export const SKILL_ICONS: Record<string, IconType> = {
  Python: SiPython,
  PostgreSQL: SiPostgresql,
  "Google Cloud Platform": SiGooglecloud,
  BigQuery: SiGooglebigquery,
  "Apache Airflow": SiApacheairflow,
  "Power BI": SiPowerbi,
  Plotly: SiPlotly,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML5: SiHtml5,
  CSS3: SiCss3,
  Docker: SiDocker,
  PySpark: SiApachespark,
  pandas: SiPandas,
  PyTorch: SiPytorch,
  "scikit-learn": SiScikitlearn,
  OpenCV: SiOpencv,
  "Google Gemini": SiGooglegemini,
  React: SiReact,
  "Next.js": SiNextdotjs,
  Express: SiExpress,
  Flask: SiFlask,
  Streamlit: SiStreamlit,
  "Looker Studio": SiLooker,
  Java: SiOpenjdk,
  NumPy: SiNumpy,
  Jupyter: SiJupyter,
};
